[package]
name = "cloaker_gui"
version = "5.0.0"
authors = ["Theron Spiegl <theron@spiegl.dev>"]
edition = "2021"

[[bin]]
name = "cloaker"
path = "src/main.rs"

[dependencies]
cloaker = { path = "../core" }
eframe = "0.36"
rfd = "0.17"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dev-dependencies]
egui_kittest = "0.36"
